# distritos_chile.py
# Fuente:
# [BCN Mapoteca Distritos](https://www.bcn.cl/siit/mapoteca/distritos)

DISTRITOS_CHILE = {
    1: [
        "arica",
        "camarones",
        "general lagos",
        "putre",
    ],

    2: [
        "alto hospicio",
        "camiña",
        "colchane",
        "huara",
        "iquique",
        "pica",
        "pozo almonte",
    ],

    3: [
        "antofagasta",
        "mejillones",
        "sierra gorda",
        "taltal",
        "tocopilla",
        "maria elena",
        "calama",
        "ollagüe",
        "san pedro de atacama",
    ],

    4: [
        "chañaral",
        "diego de almagro",
        "caldera",
        "copiapo",
        "tierra amarilla",
        "alto del carmen",
        "freirina",
        "huasco",
        "vallenar",
    ],

    5: [
        "canela",
        "illapel",
        "los vilos",
        "salamanca",
        "andacollo",
        "coquimbo",
        "la higuera",
        "la serena",
        "paihuano",
        "vicuña",
        "combarbala",
        "monte patria",
        "ovalle",
        "punitaqui",
        "rio hurtado",
    ],

    6: [
        "cabildo",
        "la ligua",
        "papudo",
        "petorca",
        "zapallar",
        "hijuelas",
        "la calera",
        "la cruz",
        "limache",
        "nogales",
        "olmue",
        "quillota",
        "quilpue",
        "villa alemana",
    ],

    7: [
        "concon",
        "juan fernandez",
        "puchuncavi",
        "quintero",
        "valparaiso",
        "viña del mar",
        "casa blanca",
        "el tabo",
        "el quisco",
        "cartagena",
        "algarrobo",
        "san antonio",
        "santo domingo",
    ],

    8: [
        "colina",
        "lampa",
        "tiltil",
        "cerrillos",
        "estacion central",
        "maipu",
        "pudahuel",
        "quilicura",
    ],

    9: [
        "cerro navia",
        "conchali",
        "huechuraba",
        "independencia",
        "lo prado",
        "quinta normal",
        "recoleta",
        "renca",
    ],

    10: [
        "la granja",
        "macul",
        "ñuñoa",
        "providencia",
        "san joaquin",
        "santiago",
    ],

    11: [
        "las condes",
        "lo barnechea",
        "vitacura",
        "la reina",
        "peñalolen",
    ],

    12: [
        "la florida",
        "pirque",
        "puente alto",
        "san jose de maipo",
        "la pintana",
        "san ramon",
        "el bosque",
    ],

    13: [
        "pedro aguirre cerda",
        "san miguel",
        "lo espejo",
        "san joaquin",
        "la cisterna",
        "el bosque",
        "san bernardo",
    ],

    14: [
        "buin",
        "calera de tango",
        "paine",
        "san bernardo",
        "alhue",
        "curacavi",
        "maria pinto",
        "melipilla",
        "san pedro",
    ],

    15: [
        "cerrillos",
        "cerro navia",
        "estacion central",
        "lo espejo",
        "maipu",
        "pudahuel",
    ],

    16: [
        "coltauco",
        "doñihue",
        "graneros",
        "las cabras",
        "mostazal",
        "peumo",
        "pichidegua",
        "quinta de tilcoco",
        "rancagua",
        "rengo",
        "requinoa",
        "san vicente",
    ],

    17: [
        "chepica",
        "chimbarongo",
        "lolol",
        "nancagua",
        "palmilla",
        "peralillo",
        "placilla",
        "pumanque",
        "san fernando",
        "santa cruz",
        "litueche",
        "la estrella",
        "marchigue",
        "navidad",
        "paredones",
        "pichilemu",
    ],

    18: [
        "curico",
        "hualañe",
        "licanten",
        "molina",
        "rauco",
        "romeral",
        "sagrada familia",
        "teno",
        "vichuquen",
    ],

    19: [
        "cauquenes",
        "chanco",
        "pelluhue",
        "constitucion",
        "curepto",
        "empedrado",
        "maule",
        "pelarco",
        "pencahue",
        "rio claro",
        "san clemente",
        "san rafael",
        "talca",
    ],

    20: [
        "chiguayante",
        "concepcion",
        "coronel",
        "florida",
        "hualpen",
        "hualqui",
        "penco",
        "san pedro de la paz",
        "santa juana",
        "talcahuano",
        "tome",
    ],

    21: [
        "cabrero",
        "laja",
        "los angeles",
        "mulchen",
        "nacimiento",
        "negrete",
        "quilaco",
        "quilleco",
        "san rosendo",
        "santa barbara",
        "tucapel",
        "yumbel",
        "alto bio bio",
        "lota",
        "arauco",
        "cañete",
        "contulmo",
        "curanilahue",
        "lebu",
        "los alamos",
        "tirua",
    ],

    22: [
        "anguol",
        "collipulli",
        "ercilla",
        "lonquimay",
        "los saucces",
        "lumaco",
        "puren",
        "renaico",
        "traiguen",
        "victoria",
        "curacautin",
        "lautaro",
        "melipeuco",
        "perquenco",
        "vilcun",
        "galvarino",
    ],

    23: [
        "carahue",
        "cholchol",
        "cunco",
        "curarrehue",
        "freire",
        "gorbea",
        "loncoche",
        "melipeuco",
        "nueva imperial",
        "padre las casas",
        "perquenco",
        "pucon",
        "saavedra",
        "temuco",
        "teodoro schmidt",
        "tolten",
        "vilcun",
        "villarrica",
    ],

    24: [
        "corral",
        "lanco",
        "los lagos",
        "mafil",
        "mariquina",
        "paillaco",
        "panguipulli",
        "valdivia",
        "futrono",
        "la union",
        "lago ranco",
        "rio bueno",
    ],

    25: [
        "calbuco",
        "cochamo",
        "fresia",
        "frutillar",
        "llanquihue",
        "los muermos",
        "maullin",
        "puerto montt",
        "puerto varas",
    ],

    26: [
        "ancud",
        "castro",
        "chonchi",
        "curaco de velez",
        "dalcahue",
        "puqueldon",
        "queilen",
        "quemchi",
        "quellon",
        "quinchao",
        "osorno",
        "puerto octay",
        "purranque",
        "puyehue",
        "rio negro",
        "san juan de la costa",
        "san pablo",
    ],

    27: [
        "aysen",
        "cisnes",
        "guaitecas",
        "cochrane",
        "ohiggins",
        "tortel",
        "coyhaique",
        "lago verde",
        "chile chico",
        "rio ibañez",
    ],

    28: [
        "antartica",
        "cabo de hornos",
        "laguna blanca",
        "natales",
        "porvenir",
        "primavera",
        "punta arenas",
        "rio verde",
        "san gregorio",
        "timaukel",
        "torres del paine",
    ],
}